### ISSUE TITLE
Allow users to chose the publish date in the "New Post" box

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Planner#1743]
![Screenshot 2024-08-27 at 10 51 00 AM](https://github.com/user-attachments/assets/17829cf1-2022-468f-9c8a-ea52759a7d72)

This is on the Content Overview screen.Because there's no publish date, it publishes immediately and also produces a strange effect in "Last Modified"
![Screenshot 2024-08-27 at 10 52 08 AM](https://github.com/user-attachments/assets/caa91145-5902-44a5-9834-10cac8b613c1)

**Comment by olatechpro** [comment]
Note: This is the second time this argument is coming up and the last time, my comment for reasons for excluding publish time in form is to prevent confusion it could causes with status but since it's coming up again, I'm making a PR for this but that doesn't take away initial problem.

For example, if you select Published status but set date to future date, the post will be scheduled, if you select Scheduled but select a past date, the post will be published etc.
